### PR TITLE
Docker Changes

### PR DESCRIPTION
**Pull request by Falchizao**
# Description

- add a description of the change

# Fixes

- add a list of issues fixed by this PR

# Screenshot (optional)

### CODE REVIEW

**Comment by leomoreno8** [comment]
OK

**Comment by Marco-Pegoraro** [comment]
OK

**Review by leomoreno8 — APPROVED** [review]
OK

**Review by Marco-Pegoraro — APPROVED** [review]
Mudanças validadas

**Review by vinibraun — APPROVED** [review]
good code fella

**Pull request merged**
